### ISSUE TITLE
How to reslove scss module

### ISSUE THREAD

**Issue by milukukoz** [maxam2017/react-18-ssr#1]
Hi, I have a problem with the path when running the server.
I used your example to try to combine the alias path.

I was successful by adding some properties inside the alias that I based on the parcel guideline
![image](https://user-images.githubusercontent.com/17758133/198866393-07d4b0eb-50b8-41e2-8308-52a8b4bf902f.png)

next, I try to run the server and it's can't resolve those aliases.
I don't exactly understand that correctly, by adding config for ts-node and using tsconfig-paths plugin to resolve those alias
its error passed
![image](https://user-images.githubusercontent.com/17758133/198872553-4f273800-f104-4eef-ad5d-041526c1b5e2.png)

and now, i have a problem with the sass module
![image](https://user-images.githubusercontent.com/17758133/198872588-b8151b9e-ced3-499f-be28-5cedea0469c6.png)

Hope to receive your response

**Comment by maxam2017** [comment]
sorry for the delayed response.

For ts type definition, you should add a definition file for scss module. (conventionally, we'd use `xxx.d.ts`)
```ts
// scss.d.ts
declare module '*.scss' {
  const content: Record<string, string>;
  export default content;
}
```

and update tsconfig...
```
"include": [..., "*.d.ts"]
```

moreover, don't forget to install `sass` and `@parcel/transformer-sass` for make parcel load scss module correctly.

**Comment by maxam2017** [comment]
oops, i found error still occurs on the server side. because ts-node can not load scss correctly.

maybe we should import built version on server side 🤔

**Comment by milukukoz** [comment]
Hi, Thanks for your concerns.
yes, I have tried many cases to solve however I think it's too hard for me, and need to do much to manage also sharing state

I factored with Next Js to have better ways
